default: &default
  adapter: postgresql
  encoding: unicode
  socket: /var/run/postgresql/.s.PGSQL.5432
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: fill_home_app

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: fill_home_app
